package org.firstinspires.ftc.teamcode.robot.subsystems;

import com.qualcomm.robotcore.hardware.HardwareMap;
import org.firstinspires.ftc.teamcode.config.RobotConstants;

/**
 * Arm subsystem.
 *
 * Owns the hardware for this mechanism and exposes high-level control
 * methods. Call update() once per loop if this subsystem needs
 * continuous control (e.g. a PID loop).
 *
 * Generated by FTC Code Utils.
 */
public class Arm {

    public Arm(HardwareMap hardwareMap) {
        // TODO: map motors, servos, and sensors here
    }

    /** Call this once per loop from the OpMode, if needed. */
    public void update() {
        // TODO: continuous control logic
    }
}
