package org.firstinspires.ftc.teamcode.robot.subsystems;

import com.qualcomm.robotcore.hardware.HardwareMap;
import com.qualcomm.robotcore.hardware.DcMotor;
import org.firstinspires.ftc.teamcode.config.HardwareNames;
import org.firstinspires.ftc.teamcode.robot.debug.TelemetryServer;
import org.firstinspires.ftc.teamcode.util.MotorUtills;
import org.firstinspires.ftc.teamcode.util.PIDController;

/**
 * TestMotor subsystem.
 *
 * Owns the hardware for this mechanism and exposes high-level control
 * methods. Call update() once per loop if this subsystem needs
 * continuous control (e.g. a PID loop).
 *
 * Generated by FTC Code Generator.
 */
public class TestMotor {

    private DcMotor testMotor;

    PIDController motorPID = new PIDController(0.005, 0.0, 0.0002, 0.0);

    private final MotorUtills motorUtils = new MotorUtills();

    public TestMotor(HardwareMap hardwareMap) {
        testMotor = hardwareMap.get(DcMotor.class, HardwareNames.TEST_MOTOR);
    }

    public void forward() {
        float motorSpeed = motorUtils.getMotorVelocityTicksPerSec(testMotor);
        testMotor.setPower(motorPID.calculate(336000, motorSpeed));
    }

    public void stop() {
        testMotor.setPower(0.0);
    }

    /** Call this once per loop from the OpMode, if needed. */
    public void update() {
        TelemetryServer.getInstance().setPidListener((p, i, d, f) -> {
            motorPID.setPIDF(p, i, d, f);
    });
    }
}
