package org.firstinspires.ftc.teamcode.robot.subsystems;

import com.qualcomm.robotcore.hardware.HardwareMap;
import com.qualcomm.robotcore.hardware.DcMotor;
import org.firstinspires.ftc.teamcode.config.HardwareNames;

/**
 * TestMotor subsystem.
 *
 * Owns the hardware for this mechanism and exposes high-level control
 * methods. Call update() once per loop if this subsystem needs
 * continuous control (e.g. a PID loop).
 *
 * Generated by FTC Code Generator.
 */
public class TestMotor {

    private DcMotor testMotor;

    public TestMotor(HardwareMap hardwareMap) {
        testMotor = hardwareMap.get(DcMotor.class, HardwareNames.TEST_MOTOR);
    }

    public void forward() {
        testMotor.setPower(0.1);
    }

    public void stop() {
        testMotor.setPower(0.0);
    }

    /** Call this once per loop from the OpMode, if needed. */
    public void update() {
        // TODO: continuous control logic
    }
}
